#!/bin/bash

run_command="$HADOOP_HOME/bin/hdfs"

if [ ! -x "$run_command" ]; then
    echo "can't find executable: '${run_command}'"
    exit 1
fi

$run_command dfsadmin -report -dead 2>&1
[ $? -ne 0 ] && exit 1

exit 0